### ISSUE TITLE
Gap filling: Add rows for missing days to exp climate

### ISSUE THREAD

**Issue by crollinson** [AileneKane/radcliffe#27]
(minor issue)
some sites don't have rows for missing dates... if we want to truly gap fill, we'll need to add these in

**Comment by AileneKane** [comment]
i believe the best way for these to get added in is as part of the gap filling, rather than by adding empty rows to the expclim.csv file. if you can think of a reason why this is not a good idea, please let me know!

**Comment by crollinson** [comment]
I'm planning to build that in, but it wasn't working like I expected the other day. It should be pretty straightforward and hopefully it'll be up & running in a few days.
