### ISSUE TITLE
Check uncentered models for number of chains and rerun as necessary. 

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/radcliffe#50]
-also update iterations for some models to make sure there are enough.

**Comment by AileneKane** [comment]
@lizzieinvancouver what is "enough"- how many interations is "enough"?

**Comment by lizzieinvancouver** [comment]
@AileneKane I usually like to end up with 4,000-8,000 samples (1,000-2,000 samples across 4 chains) and a warmup of 2,000 for each chain, but we could run a longer warmup (up to 6-8K I think we have done) to get a better n_{eff}
