### ISSUE TITLE
Add/update refs about phenology-relevant traits associated with soil moisture differences

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/radcliffe#51]
-ring vs diffuse porous (which have been linked to phenology) (Lechowics)
  -height (water transport)
  -root phenology ()

**Comment by lizzieinvancouver** [comment]
I assume we would want to say stuff about traits in the discussion ... so something like: 

Our results that functional types do not systematically respond differently to soil moisture, temperature or their interaction contrasts with some findings \citep[e.g.,][]{rollinson2012,castillioni2022effects}, but supports growing work suggesting species traits may be far more predictive (cite some big traits papers, like Diaz2016 or such). Major traits related root and leaf structure can impact species drought tolerance. For trees traits related to drought tolerance may co-vary with frost-risk, as ring-porous species are generally more drought-tolerance but risk greater damage from spring frosts compared to diffuse porous species \citep{bader2022less,wang2022contrast}; not surprisingly ring-porous species leafout later then diffuse-porous species \citep{lechowicz1984}. Such interconnections between phenology and 
other with traits occur in other systems \citep[e.g.,][]{ocheltree2020identification}, and suggests the potential for a framework to better predict the high variability of responses across species.

Refs are either in mylibrary.bib or fromLizzie2024.bib

**Comment by AileneKane** [comment]
added this to the ms!
