### ISSUE TITLE
merging RMBL data

### ISSUE THREAD

**Issue by AnneMariePanetta** [AileneKane/radcliffe#7]
Should we merge price and dunne data so that we have one RMBL site? Data from the two studies are from the same plots, and data were collected with similar methods (double check this).  Study years do not overlap; price data is from 1991-1994 and dunne data is from 1995-1998.

**Comment by AileneKane** [comment]
I have decided to keep them separate, since they are different authors and time periods. its true that the site is the same, but there are other studies for which the site is the same as well...
